# Site settings
title: "Abhishek's Resume"
description: "Abhishek's Portfolio Website."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Abhishek Kalugade"
resume_title:                   "Data Science Graduate Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "abhishek.kalugade@stonybrook.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1(631) 428-1080"
resume_contact_address:         "700 Health Sciences Drive, Stony Brook, NY"

resume_header_contact_info:     "700 Health Sciences Drive, Stony Brook, NY • +1(631) 428-1080 • abhishek.kalugade@stonybrook.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>As a Computer Science Engineering graduate with a fervor for Data Science, Machine Learning, and Artificial Intelligence, I am currently pursuing a Master's Degree in Data Science at Stony Brook University. My solid foundation in CSE fuels my passion for investigating cutting-edge ML methods, predictive analytics, and AI applications. Eager to leverage data-driven insights, I am enthusiastic about collaborating on impactful projects and discussions that harness the power of data. My immediate career goal is to contribute meaningfully to the field, applying advanced data science techniques to solve real-world challenges.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Abhishek17ak"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/abhishek-kalugade-7185a8199/"
  resume_instagram_url:         "https://www.instagram.com/abhiconic17/"
  resume_website_url:           "https://abhishek17ak.github.io/Resume/"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
